import {
  FaYoutube,
  FaInstagram,
  FaFacebook,
  FaSnapchat,
  FaTwitter,
  FaHashtag,
  FaReddit,
  FaLinkedin,
  FaGithub,
  FaStackOverflow,
  FaTwitch,
  FaSoundcloud,
  FaSpotify,
  FaApple,
  FaDiscord,
  FaTelegram,
  FaWhatsapp,
  FaSkype,
  FaAmazon,
  FaShopify,
  FaCoffee,
  FaPatreon,
  FaGlobe,
  FaBlog,
  FaEnvelope,
  FaPhone,
  FaMapMarkerAlt,
  FaCalendarAlt,
  FaFileAlt,
  FaDownload,
  FaShoppingCart,
  FaHeart,
  FaTiktok,
} from "react-icons/fa";
import {
  SiLeetcode,
  SiCodeforces,
  SiHackerrank,
  SiCodechef,
  SiGeeksforgeeks,
} from "react-icons/si";

export const Icons = {
  youtube: FaYoutube,
  instagram: FaInstagram,
  facebook: FaFacebook,
  snapchat: FaSnapchat,
  twitter: FaTwitter,
  threads: FaHashtag,
  reddit: FaReddit,
  linkedIn: FaLinkedin,
  gitHub: FaGithub,
  stackoverflow: FaStackOverflow,
  leetcode: SiLeetcode,
  codeforces: SiCodeforces,
  hackerrank: SiHackerrank,
  codechef: SiCodechef,
  geeksforgeeks: SiGeeksforgeeks,
  twitch: FaTwitch,
  soundcloud: FaSoundcloud,
  spotify: FaSpotify,
  "apple music": FaApple,
  discord: FaDiscord,
  telegram: FaTelegram,
  whatsapp: FaWhatsapp,
  skype: FaSkype,
  "amazon storefront": FaAmazon,
  shopify: FaShopify,
  "ko-fi": FaCoffee,
  "buy me a coffee": FaCoffee,
  patreon: FaPatreon,
  website: FaGlobe,
  blog: FaBlog,
  email: FaEnvelope,
  phone: FaPhone,
  globe: FaGlobe,
  mapPin: FaMapMarkerAlt,
  calendar: FaCalendarAlt,
  fileText: FaFileAlt,
  download: FaDownload,
  shoppingCart: FaShoppingCart,
  heart: FaHeart,
  tiktok: FaTiktok,
};
